<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  '#' => '',
  'Confirmation' => 'Активация',
  'Confirmation status' => 'Статус',

  'Confirmed' => 'Активирован',
  
  'Connect' => 'Подключить',
  'Continue' => 'Продолжить',
  'Create' => 'Создать',
  
  'Delete' => 'Удалить',
  'Delete account' => 'Удалить аккаунт',
  'Disconnect' => 'Отключить',
  'Finish' => 'Завершить',
  'Price Name' => 'Тариф',
  'Name Company' => 'Название компании',  
  'Dynamic String' => 'Строка подзаголовка',  
  'Image' => 'Изображение',  
  'Description' => 'Описание',  
  'Terms' => 'Сроки',  
  'Value' => 'Стоимость',    
  'Text' =>  'Текст',
  'Title Item' => 'Заголовок подпункта',
  'Section' => 'Категория',
  'Actions' => 'Действия',
  'On development stage' => 'В процессе разработки',
  'Under consideration' => 'На рассмотрении',
  'Finished' => 'Завершен',
  'New' => 'Новый',
  'img' => 'Изображение',
  '' => '',
  '' => '',
  '' => '',
  '' => '',
  '' => '',
  '' => '',
  '' => '',
  '' => '',
  '' => '',
  '' => '',
  '' => '',
  '' => '',

   
   
   
  
  'Hello' => 'Здравствуйте',
  'Information' => 'Информация',
  
  'Last login' => 'Последний вход',
  'Location' => 'Местоположение',
  'Login' => 'Логин',
  'Logout' => 'Выйти',
  'Manage users' => 'Управление пользователями',
  'Name' => 'Имя',
  'Networks' => 'Соцсети',
  'Never' => 'Ни разу',
  
  'Not blocked' => 'Пользователь незаблокирован',
  'Not found' => 'Страница не найдена',

  'General' => 'Главная страница',
  'Home page' => 'Домашняя страница',
  'Steps' => 'Этапы разработки',
  'Portfolio' => 'Портфолио',
  'Callbacks' => 'Перезвонить потом',
  'Customers' => 'Заказчики',
  'Logo' => 'Логотип',
  'Titles' => 'Заголовки',
  'Advantages' => 'Преимущества',
  'Price-list' => 'Тарифы',
  'Contacts' => 'Контакты',
  'Reviews' => 'Отзывы',
  'Widgets' => 'Виджеты',
  'Categories' => 'Категории',
  'PriceList' => 'Тариф',
  'Phone Digital' => 'Номер телефона',
  'Email' => 'Адрес почты',
  'Surname' => 'Фамилия',
  'created_at' => 'Создан:',
  'updated_at' => 'Обновлен:',
  'Settings' => 'Настройки профиля', 
  'Profile' => 'Профиль',
  'Notifications' => 'Оповещения',
  'Delete all' => 'Удалить все',
  'Mark all as read' => 'Прочитать все',
  'There are no notifications to show' => 'Нет уведомлений',
  'Password' => 'Пароль',
  'New customer created' => 'добвлен новый заказчик',
  'New callback created' => 'оставил заявку',
  'Password has been changed' => 'Пароль был изменен',
  'Permissions' => 'Разрешения',
 
  'Profile' => 'Профиль',
  'Profile details' => 'Профиль',
  'Profile details have been updated' => 'Профиль пользователя был обновлен',
  'Profile settings' => 'Настройки профиля',
  'Recover your password' => 'Восстановить пароль',

  'Registration time' => 'Время регистрации',
  'Remember me next time' => 'Запомнить меня',
  'Request new confirmation message' => 'Повторная отправка инструкций',
  'Reset your password' => 'Сбросить пароль',
  'Roles' => 'Роли',
  'Rules' => 'Правила',
  'Save' => 'Сохранить',
  'Sign in' => 'Авторизоваться',
  'Sign up' => 'Зарегистрироваться',
  'Status'=> 'Статус',
  'Unblock' => 'Разблокировать',
  'Unconfirmed' => 'Аккаунт неподтвержден',
  'Update' => 'Обновить',

  'User is not found' => 'Пользователь не найден',
  'Username' => 'Имя пользователя',
  'Users' => 'Пользователи',
  'VKontakte' => 'ВКонтакте',
  'Website' => 'Вебсайт',
  'Welcome' => 'Добро пожаловать',
  'Yandex' => 'Яндекс',

);
